# Lab Practical– 1

In [1]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


## 1) Introduction of PyTorch Tensors and Basic Operations.
- a) To understand PyTorch tensors, their initialization methods, and data types.
- b) To perform tensor operations such as arithmetic, broadcasting, indexing, and reshaping.
- c) To explore automatic differentiation using PyTorch’s Autograd system.

### Initialization and Datatypes

In [2]:
zero_dim = torch.tensor(7)
zero_dim

tensor(7)

In [3]:
one_dim = torch.tensor([7])
one_dim

tensor([7])

In [4]:
help(torch.tensor)

Help on built-in function tensor in module torch:

tensor(...)
    tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

    Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

    .. warning::

        When working with tensors prefer using :func:`torch.Tensor.clone`,
        :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
        readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
        ``t.detach().clone()``, and ``torch.tensor(t, requires_grad=True)``
        is equivalent to ``t.detach().clone().requires_grad_(True)``.

    .. seealso::

        :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
        :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

    Args:
        data (array_like): Initial data for the tensor. Can be a list, tuple,
            N

In [5]:
two_dim = torch.tensor([4,3])
two_dim

tensor([4, 3])

In [6]:
Matrix = torch.tensor([[1,2], [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [7]:
print(zero_dim.shape)
print(one_dim.shape)
print(two_dim.shape)
print(Matrix.shape)

torch.Size([])
torch.Size([1])
torch.Size([2])
torch.Size([2, 2])


In [8]:
print(zero_dim.ndim)
print(one_dim.ndim)
print(two_dim.ndim)
print(Matrix.ndim)

0
1
1
2


### Arithmetic, Broadcasting, Indicing and reshaping

In [9]:
Matrix2 = torch.tensor([[2,4],[6,8]])
Sub = Matrix2 - Matrix
Add = Matrix2 + Matrix
Mult = Matrix2 * Matrix
Div = Matrix2 / Matrix 

print(Add, "\n", Sub, "\n", Mult, "\n", Div)

tensor([[ 3,  6],
        [ 9, 12]]) 
 tensor([[1, 2],
        [3, 4]]) 
 tensor([[ 2,  8],
        [18, 32]]) 
 tensor([[2., 2.],
        [2., 2.]])


In [10]:
A = torch.tensor([[1, 2, 3], [4, 5, 6]])
B = torch.tensor([10, 20, 30])
A + B

tensor([[11, 22, 33],
        [14, 25, 36]])

In [11]:
A[1][1]

tensor(5)

In [12]:
torch.reshape(A, (A.shape[1], A.shape[0]))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### Automatic differentiation using PyTorch’s Autograd system.

We'll be trying to understand what exactly is going on here... :D 

Autogradient, which is the automatic differentiation methodology used in Torch, is a neat and efficient way to calculate the gradient of the outcome wrt to the various various depends on. We'll be going through a quick example

In [13]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(4.0, requires_grad=True)

c = (a**2) + (b**2) +(2*a*b)

In [14]:
print(c.backward())
print(a.grad) ## 2a + 2b 
print(b.grad) ## 2b + 2a

None
tensor(12.)
tensor(12.)


Now, that is the basic way of seeing how things works. In Neural Networks you use a Optimizier that uses these gradients to update the weights.

Consider now, that instead of the above, c is a final outcome from a combination of given like: $ W_a*a + W_b*b + bias$. This is the traditional Neural Network concept where to inputs are fed into one Artificial Neuron.

Going Deep into it, we can describe what is going under the hood (for autograd). Given the final outcome c in this example, assume c' is the actual values that needed to be attained. So there would be a Loss variable defined wrt to come constant c' and some values c. 

$$ L = f(c) $$

This is how the backward works now, the gradient of c is generated which is: $ \frac{\partial L}{\partial c} $. Now remember that we also need to update $ W_a*a $ & $ W_b*b$. And this is pretty simple according to the chain rule:
$$ W_a = \frac{\partial L}{\partial a} = \frac{\partial L}{\partial c} * \frac{\partial c}{\partial a} $$
$$ W_b = \frac{\partial L}{\partial b} = \frac{\partial L}{\partial c} * \frac{\partial c}{\partial b} $$

In particular, $ \frac{\partial c}{\partial a} $ and $ \frac{\partial c}{\partial b} $ are stored as rules, which in our examples would be $W_a^*$ and $W_b^*$. This is the Jacobian Matrix which forms [$W_a^*$, $W_b^*$]. Now the equations are resolved to:
$$ W = Jacobian * \frac{\partial L}{\partial c}$$

This my friends, is the reflection of the autograd of a simple system.

## 2) Perform all linear algebra operation with Tensorflow.

In [15]:
Add    = Matrix2 + Matrix
Sub    = Matrix2 - Matrix
Hadam  = Matrix2 * Matrix
Div    = Matrix2 / Matrix
MatMul = Matrix2 @ Matrix
print(Add, "\n\n", Sub, "\n\n", Hadam, "\n\n", Div, "\n\n", MatMul)

tensor([[ 3,  6],
        [ 9, 12]]) 

 tensor([[1, 2],
        [3, 4]]) 

 tensor([[ 2,  8],
        [18, 32]]) 

 tensor([[2., 2.],
        [2., 2.]]) 

 tensor([[14, 20],
        [30, 44]])


## 3) Write a program to implement AND OR gates using Perceptron.

We are working with 3 Weights: Coefficients Wx, Wy and Bias Wo. We Work on the Perceptron logic, consider weights to be integer values and not float values and let alpha learning to 1 instead of float values

In [16]:
print("x u y")
Input = [[0,0], [0,1], [1,0], [1,1]]
Wx = 0
Wy = 0
Wo = 0
Output = [False, False, False, False]

while all(Output) != True:
    for n in range(len(Input)):
        x = Input[n][0]
        y = Input[n][1]

        Solution = x | y
        Ans = Wo + x*Wx + y*Wy #Sigma Function


        Prediction = 1 if Ans >= 1 else 0 #Activation Function

        if Prediction != Solution:
            Output[n] = False

            delta = Solution - Prediction

            Wo += delta
            Wx += delta * x
            Wy += delta * y
        else:
            Output[n] = True

print(Output)

if all(Output) == True:
    print(Wo, Wx, Wy)
    for item in Input:
        print("x =", item[0], "y =", item[1], "Output =", item[0] | item[1], "Solution =",1 if (Wo + item[0]*Wx + item[1]*Wy) else 0)

x u y
[True, True, True, True]
0 1 1
x = 0 y = 0 Output = 0 Solution = 0
x = 0 y = 1 Output = 1 Solution = 1
x = 1 y = 0 Output = 1 Solution = 1
x = 1 y = 1 Output = 1 Solution = 1


In [17]:
print("x n y")
Input = [[0,0], [0,1], [1,0], [1,1]]
Wx = 0
Wy = 0
Wo = 0
Output = [False, False, False, False]

while all(Output) != True:
    for n in range(len(Input)):
        x = Input[n][0]
        y = Input[n][1]

        Solution = x & y
        Ans = Wo + x*Wx + y*Wy #Sigma Function


        Prediction = 0 if Ans <= 0 else 1 #Activation Function

        if Prediction != Solution:
            Output[n] = False

            delta = Solution - Prediction

            Wo += delta
            Wx += delta * x
            Wy += delta * y
        else:
            Output[n] = True

print(Output)

if all(Output) == True:
    print(Wo, Wx, Wy)
    for item in Input:
        print("x =", item[0], "y =", item[1], "Output =", item[0] & item[1], "Solution =", 0 if (Wo + item[0]*Wx + item[1]*Wy) <= 0 else 1)

x n y
[True, True, True, True]
-2 2 1
x = 0 y = 0 Output = 0 Solution = 0
x = 0 y = 1 Output = 0 Solution = 0
x = 1 y = 0 Output = 0 Solution = 0
x = 1 y = 1 Output = 1 Solution = 1


## 4) Implementation of XOR Problem using PyTorch Neural Network.

In [18]:
import torch.nn as nn

In [19]:
Label_XOR = torch.tensor([[0.],[1.],[1.],[0.]])
Q = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])

We have to recall that XOR actually requires two lines of separation and cannot be just identified with a input -> neuron, but requires another additional scrutiny.

In [20]:
class XOR(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 2)   # hidden layer
        self.output = nn.Linear(2, 1)   # output layer

    def forward(self, x):
        x = self.hidden(x)
        x = torch.sigmoid(x)
        x = self.output(x)
        return x

In [21]:
model = XOR()
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

In [22]:
epochs = 5000

for epoch in range(epochs):
    # 1. Forward pass
    y_pred = model(Q)

    # 2. Compute loss
    loss = criterion(y_pred, Label_XOR)

    # 3. Backward pass
    optimizer.zero_grad()
    loss.backward()

    # 4. Update weights
    optimizer.step()

    # Logging
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.7006
Epoch 100, Loss: 0.6931
Epoch 200, Loss: 0.6931
Epoch 300, Loss: 0.6929
Epoch 400, Loss: 0.6928
Epoch 500, Loss: 0.6925
Epoch 600, Loss: 0.6919
Epoch 700, Loss: 0.6906
Epoch 800, Loss: 0.6873
Epoch 900, Loss: 0.6771
Epoch 1000, Loss: 0.6456
Epoch 1100, Loss: 0.5707
Epoch 1200, Loss: 0.3922
Epoch 1300, Loss: 0.1975
Epoch 1400, Loss: 0.1137
Epoch 1500, Loss: 0.0767
Epoch 1600, Loss: 0.0570
Epoch 1700, Loss: 0.0450
Epoch 1800, Loss: 0.0370
Epoch 1900, Loss: 0.0313
Epoch 2000, Loss: 0.0271
Epoch 2100, Loss: 0.0239
Epoch 2200, Loss: 0.0213
Epoch 2300, Loss: 0.0193
Epoch 2400, Loss: 0.0175
Epoch 2500, Loss: 0.0161
Epoch 2600, Loss: 0.0149
Epoch 2700, Loss: 0.0138
Epoch 2800, Loss: 0.0129
Epoch 2900, Loss: 0.0121
Epoch 3000, Loss: 0.0114
Epoch 3100, Loss: 0.0107
Epoch 3200, Loss: 0.0102
Epoch 3300, Loss: 0.0096
Epoch 3400, Loss: 0.0092
Epoch 3500, Loss: 0.0088
Epoch 3600, Loss: 0.0084
Epoch 3700, Loss: 0.0080
Epoch 3800, Loss: 0.0077
Epoch 3900, Loss: 0.0074
Epoch 4000, 

In [23]:
with torch.no_grad():
    logits = model(Q)
    preds = (logits > 0).float()

    print("Logits:\n", logits)
    print("Predictions:\n", preds)
    print("Targets:\n", Label_XOR)

Logits:
 tensor([[-5.2970],
        [ 5.3730],
        [ 4.9939],
        [-5.4524]])
Predictions:
 tensor([[0.],
        [1.],
        [1.],
        [0.]])
Targets:
 tensor([[0.],
        [1.],
        [1.],
        [0.]])


## 5) Implement Simple below Neural Network to solve regression problem.

In [29]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [31]:
df = pd.read_csv('house_price_full+(2) - house_price_full+(2).csv')

x = df[['bedrooms', 'sqft_living']].values.astype('float32')
y = df[['price']].values.astype('float32')

print(type(x))

<class 'numpy.ndarray'>


In [32]:
scaler_x = StandardScaler()
scaler_y = StandardScaler()

In [33]:
x_scaled = scaler_x.fit_transform(x)
y_scaled = scaler_y.fit_transform(y)

In [34]:
x_t = torch.tensor(x_scaled, dtype=torch.float32)
y_t = torch.tensor(y_scaled, dtype=torch.float32)

In [35]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(2, 2),
            nn.ReLU(),
            nn.Linear(2, 1)
        )
    def forward(self, x):
        return self.net(x)

model = Model()

In [36]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [37]:
epochs = 20000
for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(x_t)
    loss = criterion(outputs, y_t)
    loss.backward()
    optimizer.step()

    if epoch % 5000 == 0:
        print("Epoch", epoch, "Loss:", loss.item())

Epoch 0 Loss: 1.9380099773406982
Epoch 5000 Loss: 0.4687226116657257
Epoch 10000 Loss: 0.4688197374343872
Epoch 15000 Loss: 0.4688064455986023


In [38]:
# Predictions
pred_scaled = model(x_t).detach().numpy()
pred_real = scaler_y.inverse_transform(pred_scaled)

for i in range(10):
    print(f"Input: {x[i]} => Predicted: {pred_real[i][0]:.2f}, Target: {y[i][0]:.2f}")

Input: [   3. 1340.] => Predicted: 337106.78, Target: 313000.00
Input: [   5. 3650.] => Predicted: 983903.44, Target: 2384000.00
Input: [   3. 1930.] => Predicted: 452736.59, Target: 342000.00
Input: [   3. 2000.] => Predicted: 469679.38, Target: 420000.00
Input: [   4. 1940.] => Predicted: 447986.38, Target: 550000.00
Input: [  2. 880.] => Predicted: 383080.38, Target: 490000.00
Input: [   2. 1350.] => Predicted: 475192.28, Target: 335000.00
Input: [   4. 2710.] => Predicted: 690562.50, Target: 482000.00
Input: [   3. 2430.] => Predicted: 605144.00, Target: 452500.00
Input: [   4. 1520.] => Predicted: 315672.16, Target: 640000.00
